DefaultContentLanguage = "en"
baseURL = "https://averywagar.com"
disqusShortname = "averywagar"
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "UA-102498484-1"
languageCode = "en"
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
summarylength = 10
theme = "anatole"
title = "Software Engineer"
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 100
[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/post/"
weight = 200
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 300
[[menu.main]]
identifier = "work"
name = "Work"
url = "/work/"
weight = 300
[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 400
[params]
author = "Avery Wagar"
contactFormAction = "https://formspree.io/f/mgerwyan"
copyright = "2003-2025"
customCss = []
customJs = []
description = "Software Engineer"
doNotLoadAnimations = false
favicon = "favicons/"
images = ["img/site-feature-image.png"]
keywords = ""
mainSections = ["post"]
profilePicture = "img/IMG_5231.png"
title = "Avery Wagar"
[params.math]
enable = false
use = "katex"
[params.simpleAnalytics]
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/ajmwagar/"
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/ajmwagar"
[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/ajmwagar/"
[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "/contact"
[[params.socialIcons]]
icon = "fas fa-rss"
title = "rss"
url = "/post/index.xml"
