baseurl = "https://averywagar.com"
languageCode = "en-us"
theme = "hello-friend-ng"

googleAnalytics = "UA-102498484-1"
disqusShortname = "averywagar"
# DisqusShortname = "averywagar"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = true
comments = true

[blackfriday]
  hrefTargetBlank = true

[permalinks]
  posts = "/posts/:year/:month/:title/"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Homepage and blog by Avery Wagar"
  keywords = "homepage, blog, science, informatics, development, programming"
  images = [""]
  comments = true

  homeSubtitle = "Software Developer"

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  gitUrl = "https://github.com/ajmwagar/blog/commit/"

# Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/ajmwagar/"

  [[params.social]]
    name = "email"
    url  = "mailto:&lt;script type=&quot;text/javascript&quot;&gt;eval(unescape(&quot;%63%6b%66%76%73%36%36%3d%5b%27%25%36%31%25%37%36%25%36%35%25%37%32%25%37%39%27%2c%5b%27%25%36%33%25%36%33%27%2c%27%25%37%37%25%36%31%25%36%37%25%36%31%25%37%32%27%5d%2e%72%65%76%65%72%73%65%28%29%2e%6a%6f%69%6e%28%27%2e%27%29%5d%2e%6a%6f%69%6e%28%27%40%27%29%3b%69%67%61%71%7a%30%31%3d%27%6d%61%69%6c%74%6f%3a%6d%65%27%3b%64%6f%63%75%6d%65%6e%74%2e%77%72%69%74%65%28%69%67%61%71%7a%30%31%2e%6c%69%6e%6b%28%27%6d%61%69%27%2b%27%6c%74%6f%3a%27%2b%63%6b%66%76%73%36%36%29%29%3b&quot;));&lt;/script&gt;" 
  [[params.social]]
    name = "github"
    url  = "https://github.com/ajmwagar/"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/ajmwagar/"

[languages]
  [languages.en]
    title = "Avery Wagar"
    subtitle = "Software Developer"
    keywords = ""
    copyright = "Avery Wagar"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd /home/ajmwagar"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    # [languages.en.menu]
    #   [[languages.en.menu.main]]
    #     identifier = "about"
    #     name = "About"
    #     url = "/about"
    #   [[languages.en.menu.main]]
    #     identifier = "showcase"
    #     name = "Showcase"
    #     url = "/showcase"
[taxonomies]
  tag      = "tags"
  category = ""

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "work"
    name       = "Work"
    url        = "/work"
